# Example parameters. Modify these for your environment.
parameters:
  satellite_fqdn: satellite.example.com
  satellite_org: default
  satellite_key: SOE
  puppet_environment: production
  public_network_id: 6832642a-00c0-494c-b513-94c60ee435f1
  nameservers: 10.3.76.2
  key_name: msolberg
  glance_image: rhel-guest-image-7.2-20151102.0
  jenkins_url: jenkins.example.com
  jenkins_job_name: spring-webapp
